### ISSUE TITLE
Issue with adding dependency

### ISSUE THREAD

**Issue by UttamPanchasara** [PrivacyStreams/PrivacyStreams#9]
I just tried to add : compile 'io.github.privacystreams:privacystreams-android-sdk:0.1.5'
 it's getting fail with error Message : FAILED TO RESOLVE

**Comment by ylimit** [comment]
Hi, our repo was just moved from `com.github.privacystreams:privacystreams-core:0.1.4` to `io.github.privacystreams:privacystreams-android-sdk:0.1.5`. Please wait some time (about 1 day) until the new groupId is approved.
Before that, you can install PrivacyStreams from source.

**Comment by ylimit** [comment]
Hi. You should now be able to use `io.github.privacystreams:privacystreams-android-sdk:0.1.5` to import PrivacyStreams library. :-)
